"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


APP_NAME = 'KTK REGISTER'
APP = ['window.py']
DATA_FILES = [
    ('db', ['ktk.json']),
    ('pictures', ['font.jpg'])
]
OPTIONS = {
    'packages': ['PIL'],
    'iconfile': 'ico.icns'
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
